CREATE TABLE Cities
(CityID INT
 PRIMARY KEY IDENTITY NOT NULL, 
 [Name] VARCHAR(50)
);
CREATE TABLE Customers
(CustomerID INT
 PRIMARY KEY IDENTITY NOT NULL, 
 [Name]     VARCHAR(50), 
 Birthday   DATE, 
 CityID     INT, 
 CONSTRAINT PK_Cities_Customers FOREIGN KEY(CityID) REFERENCES Cities(CityID)
);
CREATE TABLE Orders
(OrderID    INT
 PRIMARY KEY IDENTITY NOT NULL, 
 CustomerID INT, 
 CONSTRAINT PK_Orders_Customers FOREIGN KEY(CustomerID) REFERENCES Customers(CustomerID)
);
CREATE TABLE ItemTypes
(ItemTypeID INT
 PRIMARY KEY IDENTITY NOT NULL, 
 [Name]     VARCHAR(50)
);
CREATE TABLE Items
(ItemID     INT
 PRIMARY KEY IDENTITY NOT NULL, 
 [Name]     VARCHAR(50), 
 ItemTypeID INT, 
 CONSTRAINT PK_Items_ItemTypes FOREIGN KEY(ItemTypeID) REFERENCES ItemTypes(ItemTypeID)
);
CREATE TABLE OrderItems
(OrderID INT, 
 ItemID  INT, 
 CONSTRAINT PK_OrderItems PRIMARY KEY(OrderID, ItemID), 
 CONSTRAINT PK_OrderItems_Orders FOREIGN KEY(OrderID) REFERENCES Orders(OrderID), 
 CONSTRAINT PK_OrderItems_Items FOREIGN KEY(ItemID) REFERENCES Items(ItemID)
);