CREATE DATABASE SoftUni

USE SoftUni

CREATE TABLE Towns (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
[Name] VARCHAR(30) NOT NULL
);

CREATE TABLE Addresses (
Id INT PRIMARY KEY IDENTITY (1,1) NOT NULL,
AddressText VARCHAR(50),
TownId INT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
);

CREATE TABLE Departments (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
Name VARCHAR (50) NOT NULL
);

CREATE TABLE Employees (
Id INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
FirstName VARCHAR(30) NOT NULL,
MiddleName VARCHAR(30) NOT NULL,
LastName VARCHAR(30) NOT NULL,
JobTitle VARCHAR(30) NOT NULL,
DepartmentId INT FOREIGN KEY REFERENCES Departments (Id) NOT NULL,
HireDate VARCHAR(30) NOT NULL,
Salary DECIMAL(6,2) NOT NULL,
AddressId VARCHAR(30)
);

