SELECT CAST(24.56 AS INT);
SELECT CAST(GETDATE() AS NVARCHAR);
SELECT CONVERT(INT, 24.56);
USE SoftUni;
SELECT ProjectId, 
       Name, 
       ISNULL(CAST(EndDate AS VARCHAR), 'Not complete yet')
FROM Projects;
SELECT ProjectId, 
       Name
FROM Projects
ORDER BY Name
OFFSET 7 ROWS FETCH NEXT 10 ROWS ONLY;
SELECT ProjectId
FROM Projects
ORDER BY ProjectId DESC
OFFSET 2 ROWS FETCH NEXT 2 ROWS ONLY;